// Code generated by genalias. DO NOT EDIT.

package nmea

import "github.com/tamalmaity-dev/nmea-go-parser/value"

// Re-exports of the value package, so that the names this module
// exported before the value types moved out of this package keep working.
//
// The type aliases are the load-bearing ones: an alias is the same type,
// not a new definition, so the two spellings are interchangeable.

// Types.
type (
	Axis             = value.Axis
	Constellation    = value.Constellation
	Coordinate       = value.Coordinate
	Date             = value.Date
	Feature          = value.Feature
	FeatureEvidence  = value.FeatureEvidence
	FixQuality       = value.FixQuality
	Hemisphere       = value.Hemisphere
	NavStatus        = value.NavStatus
	NavigationStatus = value.NavigationStatus
	Side             = value.Side
	SignalDigit      = value.SignalDigit
	SignalID         = value.SignalID
	StatusFlag       = value.StatusFlag
	SystemID         = value.SystemID
	TOD              = value.TOD
	VER              = value.VER
	Version          = value.Version
	VersionDetector  = value.VersionDetector
	VersionInfo      = value.VersionInfo
	VersionReporter  = value.VersionReporter
)

// Constants. The type is inferred from the value.
const (
	AxisLatitude         = value.AxisLatitude
	AxisLongitude        = value.AxisLongitude
	ConstellationBeiDou  = value.ConstellationBeiDou
	ConstellationGLONASS = value.ConstellationGLONASS
	ConstellationGPS     = value.ConstellationGPS
	ConstellationGalileo = value.ConstellationGalileo
	ConstellationMixed   = value.ConstellationMixed
	ConstellationNavIC   = value.ConstellationNavIC
	ConstellationQZSS    = value.ConstellationQZSS
	ConstellationSBAS    = value.ConstellationSBAS
	ConstellationUnknown = value.ConstellationUnknown
	DigitNone            = value.DigitNone
	East                 = value.East
	FeatureFAA           = value.FeatureFAA
	FeatureGroundSpeed   = value.FeatureGroundSpeed
	FeatureNavStatus     = value.FeatureNavStatus
	FeatureRangeScale    = value.FeatureRangeScale
	FeatureSignalID      = value.FeatureSignalID
	FeatureSystemID      = value.FeatureSystemID
	FlagFalse            = value.FlagFalse
	FlagLeft             = value.FlagLeft
	FlagModeAuto         = value.FlagModeAuto
	FlagModeManual       = value.FlagModeManual
	FlagNo               = value.FlagNo
	FlagRight            = value.FlagRight
	FlagTrue             = value.FlagTrue
	FlagUnknown          = value.FlagUnknown
	FlagYes              = value.FlagYes
	HemisphereUnknown    = value.HemisphereUnknown
	NavStatusCaution     = value.NavStatusCaution
	NavStatusNotValid    = value.NavStatusNotValid
	NavStatusSafe        = value.NavStatusSafe
	NavStatusUnknown     = value.NavStatusUnknown
	NavStatusUnsafe      = value.NavStatusUnsafe
	North                = value.North
	QualityDGPS          = value.QualityDGPS
	QualityEstimated     = value.QualityEstimated
	QualityGPS           = value.QualityGPS
	QualityManual        = value.QualityManual
	QualityNone          = value.QualityNone
	QualityPPS           = value.QualityPPS
	QualityRTKFixed      = value.QualityRTKFixed
	QualityRTKFloat      = value.QualityRTKFloat
	QualitySimulation    = value.QualitySimulation
	QualityUnknown       = value.QualityUnknown
	SideLeft             = value.SideLeft
	SideRight            = value.SideRight
	SideUnknown          = value.SideUnknown
	SignalIDAll          = value.SignalIDAll
	SignalIDB1A          = value.SignalIDB1A
	SignalIDB1C          = value.SignalIDB1C
	SignalIDB1I          = value.SignalIDB1I
	SignalIDB1Q          = value.SignalIDB1Q
	SignalIDB2I          = value.SignalIDB2I
	SignalIDB2Q          = value.SignalIDB2Q
	SignalIDB2a          = value.SignalIDB2a
	SignalIDB2b          = value.SignalIDB2b
	SignalIDB3A          = value.SignalIDB3A
	SignalIDB3I          = value.SignalIDB3I
	SignalIDB3Q          = value.SignalIDB3Q
	SignalIDE1a          = value.SignalIDE1a
	SignalIDE1b          = value.SignalIDE1b
	SignalIDE5a          = value.SignalIDE5a
	SignalIDE5b          = value.SignalIDE5b
	SignalIDE6a          = value.SignalIDE6a
	SignalIDE6bc         = value.SignalIDE6bc
	SignalIDL1           = value.SignalIDL1
	SignalIDL1C          = value.SignalIDL1C
	SignalIDL1M          = value.SignalIDL1M
	SignalIDL1P          = value.SignalIDL1P
	SignalIDL1S          = value.SignalIDL1S
	SignalIDL2           = value.SignalIDL2
	SignalIDL2CL         = value.SignalIDL2CL
	SignalIDL2CM         = value.SignalIDL2CM
	SignalIDL2P          = value.SignalIDL2P
	SignalIDL5A          = value.SignalIDL5A
	SignalIDL5I          = value.SignalIDL5I
	SignalIDL5Q          = value.SignalIDL5Q
	SignalIDUnknown      = value.SignalIDUnknown
	South                = value.South
	StatusInvalid        = value.StatusInvalid
	StatusValid          = value.StatusValid
	StatusWarning        = value.StatusWarning
	SystemIDBeiDou       = value.SystemIDBeiDou
	SystemIDGLONASS      = value.SystemIDGLONASS
	SystemIDGPS          = value.SystemIDGPS
	SystemIDGalileo      = value.SystemIDGalileo
	SystemIDNavIC        = value.SystemIDNavIC
	SystemIDNone         = value.SystemIDNone
	SystemIDQZSS         = value.SystemIDQZSS
	West                 = value.West
)

// Variables.
var (
	LatestVersion = value.LatestVersion
	V2_00         = value.V2_00
	V2_01         = value.V2_01
	V2_10         = value.V2_10
	V2_20         = value.V2_20
	V2_30         = value.V2_30
	V3_00         = value.V3_00
	V3_01         = value.V3_01
	V4_00         = value.V4_00
	V4_10         = value.V4_10
	V4_11         = value.V4_11
	V4_30         = value.V4_30
)

// Functions. Go has no func alias, so these are function values.
var (
	AsVER                   = value.AsVER
	FeatureIntroduced       = value.FeatureIntroduced
	FeatureName             = value.FeatureName
	FeatureOnly             = value.FeatureOnly
	FeaturesNavAndFAA       = value.FeaturesNavAndFAA
	FeaturesSystemAndSignal = value.FeaturesSystemAndSignal
	FormatBearing           = value.FormatBearing
	FormatCoordinate        = value.FormatCoordinate
	FormatDMS               = value.FormatDMS
	FormatGPS               = value.FormatGPS
	FormatLatitude          = value.FormatLatitude
	FormatLongitude         = value.FormatLongitude
	FormatMetres            = value.FormatMetres
	FormatNauticalMiles     = value.FormatNauticalMiles
	FormatPosition          = value.FormatPosition
	FormatSpeedKnots        = value.FormatSpeedKnots
	IsBlank                 = value.IsBlank
	IsSBASPRN               = value.IsSBASPRN
	KnownTalkers            = value.KnownTalkers
	LatDir                  = value.LatDir
	LonDir                  = value.LonDir
	NewDate                 = value.NewDate
	NewVersionDetector      = value.NewVersionDetector
	ParseCoordinate         = value.ParseCoordinate
	ParseDate               = value.ParseDate
	ParseFieldFloat         = value.ParseFieldFloat
	ParseFieldInt           = value.ParseFieldInt
	ParseFixQuality         = value.ParseFixQuality
	ParseHemisphere         = value.ParseHemisphere
	ParseNavStatus          = value.ParseNavStatus
	ParseNavigationStatus   = value.ParseNavigationStatus
	ParseSide               = value.ParseSide
	ParseSignalID           = value.ParseSignalID
	ParseStatusFlag         = value.ParseStatusFlag
	ParseSystemID           = value.ParseSystemID
	ParseTOD                = value.ParseTOD
	ParseVersion            = value.ParseVersion
	SystemIDOf              = value.SystemIDOf
	TalkerConstellation     = value.TalkerConstellation
	TalkerSystemID          = value.TalkerSystemID
)
