// Code generated by genalias. DO NOT EDIT.

package nmea

import "github.com/tamalmaity-dev/nmea-go-parser/wire"

// Re-exports of the value package, so that the names this module
// exported before the value types moved out of this package keep working.
//
// The type aliases are the load-bearing ones: an alias is the same type,
// not a new definition, so the two spellings are interchangeable.

// Types.
type (
	ChecksumStatus  = wire.ChecksumStatus
	DecodedSentence = wire.DecodedSentence
	LineSplitter    = wire.LineSplitter
	Sentence        = wire.Sentence
	TagBlock        = wire.TagBlock
	TagBlockField   = wire.TagBlockField
	Type            = wire.Type
)

// Constants. The type is inferred from the value.
const (
	ChecksumAbsent        = wire.ChecksumAbsent
	ChecksumInvalid       = wire.ChecksumInvalid
	ChecksumMalformed     = wire.ChecksumMalformed
	ChecksumValid         = wire.ChecksumValid
	DefaultMaxLineLength  = wire.DefaultMaxLineLength
	SentenceStart         = wire.SentenceStart
	SentenceStartEnclosed = wire.SentenceStartEnclosed
	TagBlockSeparator     = wire.TagBlockSeparator
	TypeAAM               = wire.TypeAAM
	TypeAPB               = wire.TypeAPB
	TypeBOD               = wire.TypeBOD
	TypeBWC               = wire.TypeBWC
	TypeBWR               = wire.TypeBWR
	TypeDPT               = wire.TypeDPT
	TypeDTM               = wire.TypeDTM
	TypeGBS               = wire.TypeGBS
	TypeGGA               = wire.TypeGGA
	TypeGLL               = wire.TypeGLL
	TypeGNS               = wire.TypeGNS
	TypeGRS               = wire.TypeGRS
	TypeGSA               = wire.TypeGSA
	TypeGST               = wire.TypeGST
	TypeGSV               = wire.TypeGSV
	TypeHDG               = wire.TypeHDG
	TypeHDT               = wire.TypeHDT
	TypeMTW               = wire.TypeMTW
	TypeMWD               = wire.TypeMWD
	TypeMWV               = wire.TypeMWV
	TypeOSD               = wire.TypeOSD
	TypeRMB               = wire.TypeRMB
	TypeRMC               = wire.TypeRMC
	TypeROT               = wire.TypeROT
	TypeRSA               = wire.TypeRSA
	TypeRTE               = wire.TypeRTE
	TypeTHS               = wire.TypeTHS
	TypeTXT               = wire.TypeTXT
	TypeVBW               = wire.TypeVBW
	TypeVER               = wire.TypeVER
	TypeVHW               = wire.TypeVHW
	TypeVLW               = wire.TypeVLW
	TypeVTG               = wire.TypeVTG
	TypeWCV               = wire.TypeWCV
	TypeWPL               = wire.TypeWPL
	TypeXTE               = wire.TypeXTE
	TypeZDA               = wire.TypeZDA
)

// Functions. Go has no func alias, so these are function values.
var (
	Checksum        = wire.Checksum
	DataTypeOf      = wire.DataTypeOf
	Frame           = wire.Frame
	FrameWith       = wire.FrameWith
	NewLineSplitter = wire.NewLineSplitter
	ParseSentence   = wire.ParseSentence
	ParseTagBlock   = wire.ParseTagBlock
	Split           = wire.Split
	TrimDecorations = wire.TrimDecorations
	Valid           = wire.Valid
	Validate        = wire.Validate
)
